name: Integración continua

on:
  push:
  pull_request:

jobs:
  pruebas:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código
        uses: actions/checkout@v7
      - name: Configurar Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Ejecutar pruebas
        run: python verificar.py
